networks:
  proxy-network:
    external: true

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${PATH_SYSTEM_CONFIG}/prowlarr:/config
    networks:
      - proxy-network
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${PATH_SYSTEM_CONFIG}/radarr:/config
      - ${PATH_MEDIA_STORAGE}:/data
    networks:
      - proxy-network
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${PATH_SYSTEM_CONFIG}/sonarr:/config
      - ${PATH_MEDIA_STORAGE}:/data
    networks:
      - proxy-network
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${PATH_SYSTEM_CONFIG}/bazarr:/config
      - ${PATH_MEDIA_STORAGE}:/data
    networks:
      - proxy-network
    restart: unless-stopped

  flaresolver:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - TZ=${TZ}
      - LOG_LEVEL=info
      - CAPTCHA_SOLVER=none
    networks:
      - proxy-network
    restart: unless-stopped