networks:
  proxy-network:
    external: true

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${PATH_SYSTEM_CONFIG}/jellyfin:/config
      - ${PATH_MEDIA_STORAGE}:/data:ro
    ports:
      - 127.0.0.1:8096:8096
    networks:
      - proxy-network
    restart: unless-stopped

  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: seerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - LOG_LEVEL=debug
    ports:
      - 127.0.0.1:5055:5055
    volumes:
      - ${PATH_SYSTEM_CONFIG}/seerr:/app/config
    networks:
      - proxy-network
    restart: unless-stopped